services:
  # Backend API Service
  - type: web
    name: monkyjam-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: HF_API_TOKEN
        sync: false
      - key: FRONTEND_URL
        fromService:
          name: monkyjam-frontend
          type: web
          property: url

  # Frontend Next.js Service
  - type: web
    name: monkyjam-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: monkyjam-api
          type: web
          property: url 